name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update README.md
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://ghost-him.github.io/feed.xml"
          readme_path: "README.md"
          max_post_count: 5
          template: "$newline - $date: [$title]($url)"
          date_format: "yyyy-mm-dd"
      - name: Update README_en.md
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://ghost-him.github.io/feed.xml"
          readme_path: "README_en.md"
          max_post_count: 5
          template: "$newline - $date: [$title]($url)"
          date_format: "yyyy-mm-dd"
